services:
  backend:
    image: stouffville-bylaws-ai/backend:latest
    build: ./backend  # Fallback if image doesn't exist
    volumes:
      - ./backend:/app  # For development
      - ./database:/database  # Mount database directory
    ports:
      - "5000:5000"
    restart: always

